# Generated by Django 4.0.10 on 2025-01-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuário Customizado', 'verbose_name_plural': 'Usuários Customizados'},
        ),
    ]
