# Generated by Django 4.0.10 on 2025-01-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_codemember_hospital_sector_delete_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='codemember',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
