# Generated by Django 4.0.10 on 2025-01-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_codemember_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codemember',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='codemember',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
