# Generated by Django 4.0.10 on 2025-01-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_codemember_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
