# Generated by Django 4.0.10 on 2025-01-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0013_sector_hospital_alter_evaluator_hospital_and_more'),
        ('users', '0007_customuser_remove_hospital_last_login_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
    ]
