# Generated by Django 4.0.10 on 2025-01-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('job_role', models.CharField(choices=[('MED', 'Médico(a)'), ('ENF', 'Enfermeiro(a)'), ('TENF', 'Técnico(a) de Enfermagem'), ('AENF', 'Auxiliar de Enfermagem'), ('FARM', 'Farmacêutico(a)'), ('TFARM', 'Técnico(a) de Farmácia'), ('FISIO', 'Fisioterapeuta'), ('TOCUP', 'Terapeuta Ocupacional'), ('NUTR', 'Nutricionista'), ('PSI', 'Psicólogo(a)'), ('ASSOC', 'Assistente Social'), ('TRAD', 'Técnico(a) em Radiologia'), ('REC', 'Recepcionista'), ('SEC', 'Secretário(a)'), ('ADM', 'Administrador(a) Hospitalar'), ('CONT', 'Contador / Analista Financeiro'), ('LIMP', 'Auxiliar de Limpeza'), ('MAQ', 'Maqueiro'), ('CENF', 'Coordenador(a) de Enfermagem'), ('AMB', 'Condutor(a) de Ambulância')], max_length=5)),
                ('evaluation_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FormSubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000)),
                ('question_hint', models.CharField(max_length=20)),
                ('question_value', models.IntegerField()),
                ('question_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ONAForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ONA_sections', models.ManyToManyField(related_name='ona_form_sections', to='data_management.formsection')),
            ],
        ),
    ]
