# Generated by Django 4.0.10 on 2025-02-18 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=20)),
                ('section_title', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Seção',
                'verbose_name_plural': 'Seções',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=80)),
                ('contact_number', models.CharField(blank=True, max_length=16)),
                ('address', models.TextField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('last_service', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitais',
            },
        ),
        migrations.CreateModel(
            name='JobRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=400, null=True)),
                ('guidance', models.TextField(max_length=400, null=True)),
                ('evidence', models.TextField(max_length=400, null=True)),
                ('core', models.BooleanField(default=False)),
                ('level', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='ONAForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_title', models.CharField(help_text='Titulo para o formulário.', max_length=80)),
                ('ONA_sections', models.ManyToManyField(help_text='Selecione as seções que você quer ter no formulário. (A ordem importa!) --- ', related_name='ona_form_sections', to='data_management.formsection')),
                ('hospital', models.ForeignKey(help_text='Indique o hospital ao qual este formulário está associado.', on_delete=django.db.models.deletion.CASCADE, to='data_management.hospital')),
            ],
            options={
                'verbose_name': 'Formulário ONA para edição',
                'verbose_name_plural': 'Formulários ONA para edição',
            },
        ),
        migrations.AddField(
            model_name='hospital',
            name='sectors',
            field=models.ManyToManyField(related_name='hospital_sectors', to='data_management.sector'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='username',
            field=models.OneToOneField(max_length=80, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FormSubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection_id', models.CharField(max_length=20)),
                ('subsection_title', models.CharField(max_length=80)),
                ('questions_level1', models.ManyToManyField(related_name='level1_questions', to='data_management.question')),
                ('questions_level2', models.ManyToManyField(related_name='level2_questions', to='data_management.question')),
            ],
            options={
                'verbose_name': 'Criar Formulário ONA',
                'verbose_name_plural': 'Criar Formulários ONA',
            },
        ),
        migrations.AddField(
            model_name='formsection',
            name='form_subsections',
            field=models.ManyToManyField(related_name='form_subsections', to='data_management.formsubsection'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='questions_level3',
            field=models.ManyToManyField(related_name='level3_questions', to='data_management.question'),
        ),
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('evaluation_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=80)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.hospital')),
                ('hospital_sector', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_sectors', to='data_management.sector')),
                ('job_role', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_job_role', to='data_management.jobroles')),
            ],
            options={
                'verbose_name': 'Avaliador',
                'verbose_name_plural': 'Avaliadores',
            },
        ),
    ]
