# Generated by Django 4.0.10 on 2025-01-08 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_management', '0001_initial'),
        ('users', '0002_codemember_hospital_sector_delete_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onaform',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.hospital'),
        ),
        migrations.AddField(
            model_name='formsubsection',
            name='questions',
            field=models.ManyToManyField(related_name='subsections_questions', to='data_management.question'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='form_subsections',
            field=models.ManyToManyField(related_name='form_sections', to='data_management.formsubsection'),
        ),
        migrations.AddField(
            model_name='evaluator',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.hospital'),
        ),
        migrations.AddField(
            model_name='evaluator',
            name='hospital_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sector'),
        ),
    ]
