# Generated by Django 4.0.10 on 2025-01-13 22:32

from django.db import migrations
from data_management.etls.ONA.ONA_etls import insert_questions,remove_questions

class Migration(migrations.Migration):
    dependencies = [
        ("data_management", "0001_initial"),
    ]

    operations = [migrations.RunPython(insert_questions, reverse_code=remove_questions)]
