# Generated by Django 4.0.10 on 2025-01-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_hint',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_value',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='evidence',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='guidance',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='result',
            field=models.IntegerField(default=0),
        ),
    ]
