# Generated by Django 4.0.10 on 2025-01-14 18:35

from django.db import migrations

from ..etls.ONA.json_reader import JSONReader
from data_management.etls.ONA.ONA_etls import insert_subsections, remove_subsections


class Migration(migrations.Migration):
    dependencies = [
        ("data_management", "0003_insert_questions"),
    ]

    operations = [
        migrations.RunPython(insert_subsections, reverse_code=remove_subsections)
    ]
