# Generated by Django 4.0.10 on 2025-01-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_rename_question_hint_question_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsection',
            name='level3',
            field=models.ManyToManyField(related_name='level3_questions', to='data_management.question'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='section_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formsection',
            name='sections_title',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formsubsection',
            name='level1',
            field=models.ManyToManyField(related_name='level1_questions', to='data_management.question'),
        ),
        migrations.AddField(
            model_name='formsubsection',
            name='level2',
            field=models.ManyToManyField(related_name='level2_questions', to='data_management.question'),
        ),
        migrations.AddField(
            model_name='formsubsection',
            name='subsection_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formsubsection',
            name='subsection_title',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onaform',
            name='form_title',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
