# Generated by Django 4.0.10 on 2025-01-14 19:35

from django.db import migrations

from ..etls.ONA.json_reader import JSONReader
from data_management.etls.ONA.ONA_etls import insert_sections, remove_sections

class Migration(migrations.Migration):
    dependencies = [
        ("data_management", "0004_insert_subsections"),
    ]

    operations = [
        migrations.RunPython(insert_sections, reverse_code=remove_sections)
    ]
