# Generated by Django 4.0.10 on 2025-01-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0005_rename_level3_formsection_questions_level3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
