# Generated by Django 4.0.10 on 2025-02-06 20:43

from django.db import migrations
from data_management.etls.ONA.ONA_etls import create_template

class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0005_insert_sections'),
    ]

    operations = [
        migrations.RunPython(create_template)
    ]
