# Generated by Django 4.0.10 on 2025-01-27 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0005_insert_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='form_subsection',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='ona_form',
        ),
        migrations.AddField(
            model_name='formsectionanswered',
            name='form_section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_section', to='data_management.formsection'),
        ),
        migrations.AddField(
            model_name='formsubsectionanswered',
            name='form_subsection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_subsection', to='data_management.formsubsection'),
        ),
        migrations.AddField(
            model_name='onaformanswered',
            name='ona_form',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_ona_form', to='data_management.onaform'),
        ),
    ]
