# Generated by Django 4.0.10 on 2025-01-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0006_alter_question_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='evidence',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='guidance',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
