# Generated by Django 4.0.10 on 2025-01-27 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0006_remove_questionawnser_form_subsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onaformanswered',
            name='evaluator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_evaluator', to='data_management.evaluator'),
        ),
    ]
