# Generated by Django 4.0.10 on 2025-02-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0006_remove_formsubsectionanswered_answered_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluator',
            name='job_role',
            field=models.CharField(choices=[('004.005', 'Process. de Roupas'), ('004.004', 'Process. de produtos'), ('004.003', 'Limpeza e Desinf. de superf'), ('004.002', 'Gestão de Infraestrutura'), ('004.001', 'Gestão de equipamentos'), ('003.007', 'Mét. endoscópicos e vid.'), ('003.006', 'Radiologia Interv.'), ('003.005', 'Medicina Nuclear'), ('003.004', 'Diagósticos por imagem'), ('003.003', 'Met. Diagósticos. e Terap.'), ('003.002', 'Anatomia Patológica e Citop'), ('003.001', 'Análises clínicas'), ('002.020', 'Atenção Domiciliar'), ('002.019', 'Atenção Primária'), ('002.018', 'Telemedicina'), ('002.017', 'Odontologia'), ('002.016', 'Atend. Pré Hospitalar'), ('002.015', 'Atendimento Oftalmológico'), ('002.014', 'Assistência Nutricional'), ('002.013', 'Assistência Farmacêutica'), ('002.012', 'Med. Hiperbárica'), ('002.011', 'Radioterapia'), ('002.010', 'Assistência Oncológica'), ('002.009', 'Assistência Nefrológica'), ('002.008', 'Assistência Hemoterápica'), ('002.007', 'Cuidados Intensivos'), ('002.006', 'Atendimento Neonatal'), ('002.005', 'Atendimento Obstétrico'), ('002.004', 'Atendimento Cirúrgico'), ('002.003', 'Atendimento Emergencial'), ('002.002', 'Atendimento Ambulatorial'), ('002.001', 'Internação'), ('001.010', 'Gestão Da Comunicação'), ('001.009', 'Gestão Da Segurança'), ('001.008', 'Gestão Do Acesso'), ('001.007', 'Gestão Da Tec. Da Inf.'), ('001.006', 'Gestão De Suprimentos'), ('001.005', 'Gestão De Pessoas'), ('001.004', 'Gestão Adm Financeira'), ('001.003', 'Prev. Controle De Infecção'), ('001.002', 'Gestão Da Qualidade'), ('001.001', 'Liderança Organizacional')], max_length=7),
        ),
    ]
