# Generated by Django 4.0.10 on 2025-02-18 17:58

from django.db import migrations

from django.db import migrations

def create_job_roles(apps, schema_editor):
    JobRole = apps.get_model('data_management', 'JobRoles')
    job_roles = [
        ("1", "Diretor "),
        ("2", "Gerente"),
        ("3", "Coordenador do Setor (Apoio / Administrativo)"),
        ("3", "Coordenador Médico"),
        ("4", "Coordenador enfermeiro"),
        ("5", "Supervisor do Setor"),
        ("6", "Enfermeiro Diarista"),
        ("7", "Médico Rotina"),
        ("8", "Avaliador Consultor Externo"),
        ("9", "Avaliador Interno da Qualidade")
    ]
    
    for code, description in job_roles:
        # Store only the description as the JobRole's name.
        JobRole.objects.create(name=description)

def remove_job_roles(apps, schema_editor):
    JobRole = apps.get_model('data_management', 'JobRoles')
    job_role_names = [
        "Diretor ",
        "Gerente",
        "Coordenador do Setor (Apoio / Administrativo)",
        "Coordenador Médico",
        "Coordenador enfermeiro",
        "Supervisor do Setor",
        "Enfermeiro Diarista",
        "Médico Rotina",
        "Avaliador Consultor Externo",
        "Avaliador Interno da Qualidade"
    ]
    for name in job_role_names:
        JobRole.objects.filter(name=name).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0007_insert_sectors'),
    ]

    operations = [
        migrations.RunPython(create_job_roles, remove_job_roles),
    ]
