# Generated by Django 4.0.10 on 2025-01-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0007_onaformanswered_evaluator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubsectionanswered',
            name='answered_questions',
        ),
        migrations.AddField(
            model_name='formsectionanswered',
            name='answered_questions_level_3',
            field=models.ManyToManyField(related_name='answered_questions_level_3', to='data_management.questionanswer'),
        ),
        migrations.AddField(
            model_name='formsubsectionanswered',
            name='answered_questions_level_1',
            field=models.ManyToManyField(related_name='answered_questions_level_1', to='data_management.questionanswer'),
        ),
        migrations.AddField(
            model_name='formsubsectionanswered',
            name='answered_questions_level_2',
            field=models.ManyToManyField(related_name='answered_questions_level_2', to='data_management.questionanswer'),
        ),
    ]
