# Generated by Django 4.0.10 on 2025-02-07 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0008_onaform_evaluator_alter_evaluator_job_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onaform',
            name='evaluator',
        ),
    ]
