# Generated by Django 4.0.10 on 2025-01-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0008_remove_formsubsectionanswered_answered_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionawnser',
            name='answer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
