# Generated by Django 4.0.10 on 2025-01-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0009_alter_questionawnser_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsectionanswered',
            name='answered_subsections',
            field=models.ManyToManyField(related_name='answered_subsections', to='data_management.formsubsectionanswered'),
        ),
        migrations.AlterField(
            model_name='onaformanswered',
            name='answered_sections',
            field=models.ManyToManyField(related_name='answered_sections', to='data_management.formsectionanswered'),
        ),
    ]
