# Generated by Django 4.0.10 on 2025-01-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0010_alter_formsectionanswered_answered_subsections_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluator',
            options={'verbose_name': 'Avaliador', 'verbose_name_plural': 'Avaliadores'},
        ),
        migrations.AlterModelOptions(
            name='formsection',
            options={'verbose_name': 'Seção', 'verbose_name_plural': 'Seções'},
        ),
        migrations.AlterModelOptions(
            name='formsubsection',
            options={'verbose_name': 'Subseção', 'verbose_name_plural': 'Subseções'},
        ),
        migrations.AlterModelOptions(
            name='onaform',
            options={'verbose_name': 'Formulário ONA', 'verbose_name_plural': 'Formulários ONA'},
        ),
        migrations.AlterModelOptions(
            name='onaformanswered',
            options={'verbose_name': 'Formulário ONA Respondido', 'verbose_name_plural': 'Formulários ONA Respondidos'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
    ]
