# Generated by Django 4.0.10 on 2025-01-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0010_insert_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluator',
            name='job_role',
            field=models.CharField(choices=[(None, 'Escolha sua profissão...'), ('MED', 'Médico(a)'), ('ENF', 'Enfermeiro(a)'), ('TENF', 'Técnico(a) de Enfermagem'), ('AENF', 'Auxiliar de Enfermagem'), ('FARM', 'Farmacêutico(a)'), ('TFARM', 'Técnico(a) de Farmácia'), ('FISIO', 'Fisioterapeuta'), ('TOCUP', 'Terapeuta Ocupacional'), ('NUTR', 'Nutricionista'), ('PSI', 'Psicólogo(a)'), ('ASSOC', 'Assistente Social'), ('TRAD', 'Técnico(a) em Radiologia'), ('REC', 'Recepcionista'), ('SEC', 'Secretário(a)'), ('ADM', 'Administrador(a) Hospitalar'), ('CONT', 'Contador / Analista Financeiro'), ('LIMP', 'Auxiliar de Limpeza'), ('MAQ', 'Maqueiro'), ('CENF', 'Coordenador(a) de Enfermagem'), ('AMB', 'Condutor(a) de Ambulância')], max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluator',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
