# Generated by Django 4.0.10 on 2025-01-15 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0011_alter_evaluator_job_role_alter_evaluator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='onaform',
            name='evaluator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='data_management.evaluator'),
        ),
    ]
