# Generated by Django 4.0.10 on 2025-01-28 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0011_alter_evaluator_options_alter_formsection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'Hospital', 'verbose_name_plural': 'Hospitais'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
    ]
