# Generated by Django 4.0.10 on 2025-01-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0012_alter_hospital_options_alter_sector_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionawnser',
            name='answered_at',
        ),
        migrations.AddField(
            model_name='onaformanswered',
            name='answered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
