# Generated by Django 4.0.10 on 2025-01-15 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_management', '0012_onaform_evaluator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=80)),
                ('contact_number', models.CharField(blank=True, max_length=16)),
                ('address', models.TextField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_service', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=1)),
                ('name', models.OneToOneField(max_length=80, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sectors', models.ManyToManyField(related_name='hospital_sectors', to='data_management.sector')),
            ],
        ),
        migrations.AlterField(
            model_name='evaluator',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.hospital'),
        ),
        migrations.AlterField(
            model_name='evaluator',
            name='hospital_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.sector'),
        ),
        migrations.AlterField(
            model_name='onaform',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.hospital'),
        ),
    ]
