# Generated by Django 4.0.10 on 2025-01-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0013_remove_questionawnser_answered_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionAwnser',
            new_name='QuestionAnswer',
        ),
    ]
