# Generated by Django 4.0.10 on 2025-01-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0013_sector_hospital_alter_evaluator_hospital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='is_superuser',
        ),
    ]
