# Generated by Django 4.0.10 on 2025-01-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0014_rename_questionanswer_questionanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubsectionanswered',
            name='answered_questions_level_1',
        ),
        migrations.RemoveField(
            model_name='formsubsectionanswered',
            name='answered_questions_level_2',
        ),
        migrations.RemoveField(
            model_name='formsubsectionanswered',
            name='form_subsection',
        ),
        migrations.RemoveField(
            model_name='onaformanswered',
            name='answered_sections',
        ),
        migrations.RemoveField(
            model_name='onaformanswered',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='onaformanswered',
            name='ona_form',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='question',
        ),
        migrations.DeleteModel(
            name='FormSectionAnswered',
        ),
        migrations.DeleteModel(
            name='FormSubsectionAnswered',
        ),
        migrations.DeleteModel(
            name='ONAFormAnswered',
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
    ]
