# Generated by Django 4.0.10 on 2025-01-15 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_management', '0014_remove_hospital_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='username',
            field=models.OneToOneField(max_length=80, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
