# Generated by Django 4.0.10 on 2025-01-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0015_hospital_username_alter_hospital_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
