# Generated by Django 4.0.10 on 2025-01-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0016_alter_hospital_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onaform',
            name='evaluator',
        ),
    ]
