# Generated by Django 4.0.10 on 2025-01-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0017_remove_onaform_evaluator'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='value',
            field=models.TextField(default=0, max_length=400, null=True),
        ),
    ]
