# Generated by Django 4.0.10 on 2025-01-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0018_question_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='value',
        ),
    ]
