# Generated by Django 4.0.10 on 2025-01-21 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0019_remove_question_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAwnser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('form_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_answers', to='data_management.formsection')),
                ('form_subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_answers', to='data_management.formsubsection')),
                ('ona_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_answers', to='data_management.onaform')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='data_management.question')),
            ],
        ),
    ]
