# Generated by Django 4.0.10 on 2025-01-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0020_questionawnser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionawnser',
            name='form_section',
        ),
        migrations.CreateModel(
            name='ONAFormAnswered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_sections', models.ManyToManyField(related_name='answered_sections', to='data_management.questionawnser')),
            ],
        ),
        migrations.CreateModel(
            name='FormSubsectionAnswered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_questions', models.ManyToManyField(related_name='answered_questions', to='data_management.questionawnser')),
            ],
        ),
        migrations.CreateModel(
            name='FormSectionAnswered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_subsections', models.ManyToManyField(related_name='answered_subsections', to='data_management.questionawnser')),
            ],
        ),
    ]
