# Generated by Django 4.0.10 on 2025-01-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0021_remove_questionawnser_form_section_onaformanswered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionawnser',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='questionawnser',
            name='answer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
