# Generated by Django 4.0.10 on 2025-02-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onaformdistribution',
            old_name='distribution',
            new_name='distribution_by_section',
        ),
        migrations.RemoveField(
            model_name='onaformdistribution',
            name='total_distribution',
        ),
        migrations.AddField(
            model_name='onaformdistribution',
            name='distribution_by_subsection',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='onaformdistribution',
            name='ona_answer_total_distribution',
            field=models.JSONField(default=dict),
        ),
    ]
