# Generated by Django 4.0.10 on 2025-02-03 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = []
