# Generated by Django 4.0.10 on 2025-07-03 22:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onaformdistribution',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
