# Generated by Django 4.0.10 on 2025-02-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_insert_furfield_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='comment',
            field=models.TextField(max_length=600, null=True),
        ),
    ]
