# Generated by Django 4.0.10 on 2025-07-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_onaformdistribution_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='comment',
            field=models.TextField(max_length=4000, null=True),
        ),
    ]
